version: '3'


services:

  flask:
    build:
      context: app
    ports:
      - "32777:32777"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - flask
    ports:
      - "80:80"
