server:
  restart: always
  image: nginx
  volumes:
    - ./server/conf.d:/etc/nginx/conf.d
  links:
    - web:web
  ports:
    - "80:80"

web:
  extends:
    file: docker-compose.base.yml
    service: web
  expose:
    - "32777"
  command: gunicorn app:app -b :32777 --name app --log-level=debug --log-file=-