version: '3'


services:

  app:
    build: ./app
    command: gunicorn --bind 0.0.0.0:32777 wsgi:app
    ports:
      - "32777:32777"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
